version: '3.8'
networks:
  backend:
services:
  database:
    image: postgres:15.0
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    
    command:
      tail -f /dev/null

